part of 'package:frontend_flutter/pages/reference_sheets_view.dart';

const Map<String, List<String>> _mealLineJobs = {
  'Breakfast': [
    'Sack Cashier',
    'Sack Runner',
    'Salads',
    'Server',
    'Line Running (Left)',
    'Line Running (Right)',
    'Aloha Plate',
    'Choices',
    'Beverages',
    'Senior Cash',
    'Junior Cash',
    'Desserts',
    'Condiments Prep',
    'Condiments Host',
  ],
  'Lunch': [
    'Sack Cashier',
    'Sack Runner',
    'Salads',
    'Server',
    'Ice Cream',
    'Paninis',
    'Line Running (Left)',
    'Line Running (Right)',
    'Aloha Plate',
    'Choices',
    'Beverages',
    'Senior Cash',
    'Junior Cash',
    'Desserts',
    'Condiments Prep',
    'Condiments Host',
  ],
  'Dinner': [
    'Server',
    'Ice Cream',
    'Paninis',
    'Line Running (Left)',
    'Line Running (Right)',
    'Aloha Plate',
    'Choices',
    'Beverages',
    'Senior Cash',
    'Junior Cash',
    'Desserts',
    'Condiments Prep',
    'Condiments Host',
  ],
};

const Map<String, Map<String, Map<String, List<String>>>>
_lineReferenceCatalog = {
  'Breakfast': {
    'Sack Cashier': {
      'Setup': [
        'Put out oatmeal',
        'Put out oatmeal cups and lids',
        'Turn on cooler lights',
        'Put out donuts',
        'Put out donut utensils',
        'Unlock door when doors open',
        'Flip sign to "Open"',
        'Set up and sign into register',
      ],
      'During Shift': [
        'Ensure missionaries swipe cards',
        'Keep count of missionaries who do not swipe',
        'Ring up senior missionaries',
        'Communicate with sack runner when items run out',
      ],
      'Cleanup': [
        'Flip sign to "Closed"',
        'Lock door',
        'Log out of register',
        'Turn off cooler lights',
        'Restock drinks',
        'Put away donuts',
        'Put away oatmeal',
        'Wipe counters',
        'Vacuum area',
      ],
    },
    'Sack Runner': {
      'Setup': ['Assist sack cashier with setup tasks'],
      'During Shift': [
        'Restock items from sack room as needed',
        'Coordinate with sack cashier',
      ],
      'Cleanup': ['Assist sack cashier with cleanup tasks'],
    },
    'Salads': {
      'Setup': [
        'Put out fruit and breakfast salad items',
        'Ensure plates are stocked',
      ],
      'During Shift': [
        'Keep salad bar stocked',
        'Ensure plates remain stocked',
        'Keep oatmeal, grits, or similar items stocked and warm',
      ],
      'Cleanup': [
        'Surfaces cleaned',
        'Soup area clean',
        'Fridges wiped out',
        'Floor swept in and out of island',
        'Bowls/plates restocked',
        'Fruit shelf restocked',
        'Lettuce wraps/dressings restocked',
        'Trash emptied',
      ],
    },
    'Server': {
      'Setup': [
        'Follow the line map and set up the serving line',
        'Make sure the display plate has been put out',
        'Put 6 plates or 10 bowls out onto the hot pad before the doors open',
      ],
      'During Shift': [
        'Serve the food',
        'Communicate your needs to the runner as they come up',
      ],
      'Cleanup': [
        'Clean up the serving line and make sure the heaters and light are turned off',
      ],
    },
    'Line Running (Left)': {
      'Setup': [
        'Fill wells with water',
        'Turn on heat',
        'Turn on heating elements',
        'Put food out in correct order',
        'Get utensils',
        'Prepare plate stacks',
      ],
      'During Shift': [
        'Keep food stocked',
        'Communicate with chefs as needed',
        'Put plates out 10 at a time',
        'Keep track of plate counts',
      ],
      'Cleanup': [
        'Plates/bowls restocked',
        'Heaters off',
        'Surfaces clean and dry',
        'Drain closed and bucket empty',
        'Floors swept (including under station)',
        'Trash emptied',
      ],
    },
    'Line Running (Right)': {
      'Setup': [
        'Fill wells with water',
        'Turn on heat',
        'Turn on heating elements',
        'Put food out in correct order',
        'Get utensils',
        'Prepare plate stacks',
      ],
      'During Shift': [
        'Keep food stocked',
        'Communicate with chefs as needed',
        'Put plates out 10 at a time',
        'Keep track of plate counts',
      ],
      'Cleanup': [
        'Plates/bowls restocked',
        'Heaters off',
        'Surfaces clean and dry',
        'Drain closed and bucket empty',
        'Floors swept (including under station)',
        'Trash emptied',
      ],
    },
    'Aloha Plate': {
      'Setup': [
        'Fill wells with water',
        'Turn on heat',
        'Turn on heating elements',
        'Put food out in correct order',
        'Get utensils',
        'Prepare plate stacks',
      ],
      'During Shift': [
        'Keep food stocked',
        'Communicate with chefs as needed',
        'Put plates out 10 at a time',
        'Keep track of plate counts',
      ],
      'Cleanup': [
        'Plates/bowls restocked',
        'Heaters off',
        'Surfaces clean and dry',
        'Drain closed and bucket empty',
        'Floors swept (including under station)',
        'Trash emptied',
      ],
    },
    'Choices': {
      'Setup': [
        'Fill wells with water',
        'Turn on heat',
        'Turn on heating elements',
        'Put food out in correct order',
        'Get utensils',
        'Prepare plate stacks',
      ],
      'During Shift': [
        'Keep food stocked',
        'Communicate with chefs as needed',
        'Put plates out 10 at a time',
        'Keep track of plate counts',
      ],
      'Cleanup': [
        'Plates/bowls restocked',
        'Heaters off',
        'Surfaces clean and dry',
        'Drain closed and bucket empty',
        'Floors swept (including under station)',
        'Trash emptied',
      ],
    },
    'Beverages': {
      'Setup': [
        'Ensure all beverages are stocked',
        'Turn on beverage machines',
      ],
      'During Shift': [
        'Restock cups',
        'Check bib room for soda stock',
        'Ensure sodas are stocked',
        'Ensure juices are stocked',
        'Ensure all beverage stations remain stocked',
      ],
      'Cleanup': [
        'Milks and juices restocked',
        'Milk/soda/juice machines cleaned',
        'Cups filled',
        'Ice filled',
        'Scissors cleaned',
        'Milk trays cleaned',
        'Coke machine nozzles (dinner)',
        'Blue crates to Empire Crate Building',
        'Empire Crate Building wrapped',
        'Vitamin waters restocked',
        'BIB room checked',
      ],
    },
    'Senior Cash': {
      'Setup': ['Sign into register', 'Verify register is ready'],
      'During Shift': ['Ring up senior missionaries'],
      'Cleanup': [
        'Napkins and salt/pepper',
        'Sanitizer and paper towels',
        'Lost and found items to front desk',
        'Write next meal menu on door',
        'Refill sanitizer bottles',
        'Sweep tile floor',
      ],
    },
    'Junior Cash': {
      'Setup': ['Sign into register'],
      'During Shift': [
        'Ensure missionaries swipe cards',
        'Keep count of missionaries without cards',
      ],
      'Cleanup': [
        'Napkins and salt/pepper',
        'Sanitizer and paper towels',
        'Lost and found items to front desk',
        'Write next meal menu on door',
        'Refill sanitizer bottles',
        'Sweep tile floor',
      ],
    },
    'Desserts': {
      'Setup': [
        'Put out desserts',
        'Breakfast: donuts',
        'Lunch/Dinner: cookies or assigned desserts',
        'Put out plates',
        'Put out utensils',
      ],
      'During Shift': ['Keep desserts stocked', 'Keep utensils stocked'],
      'Cleanup': [
        'Dirty trays/utensils taken to scullery',
        'Dessert plates restocked',
        'Desserts put away in correct spot',
        'Counters/surfaces cleaned and dried',
        'Floor swept',
        'Cereal bowls restocked',
        'Silverware restocked',
      ],
    },
    'Condiments Prep': {
      'Setup': [
        'Ensure condiment cart is full',
        'Assist condiments host with setup',
      ],
      'During Shift': [
        'Keep condiments stocked',
        'Prepare condiments for next meal',
        'If dinner: prepare condiments for breakfast bar next day',
      ],
      'Cleanup': [
        'Enough prepped for next meal',
        'Specialty condiments prepped',
        'PB, J, and butter prepped',
        'Prep surfaces cleaned and dried',
        'Toaster station cleaned and restocked',
        'Condiment dispensers clean and full',
        'Pump station swept under',
        'Fruit bar surfaces cleaned and dried',
        'Bowls/plates restocked on fruit bar',
      ],
    },
    'Condiments Host': {
      'Setup': [
        'Turn on fruit bar cooler',
        'Put out fruit (4 shotgun pans of fruit, 2 of specialty food)',
        'Put out any special condiments to salad bar',
        'Put up allergen signs',
        'Put utensils in the peanut butter, and butter next to Aloha plate',
        'Make sure the condiment stands are stocked',
        'Put spoons in the fruit',
      ],
      'During Shift': [
        'Ensure everything stays stocked: fruit, condiments, and salad bar condiments',
      ],
      'Cleanup': [
        'Wrap and put away the specialty food',
        'Wrap the fruit, leave it in place, and leave the cooler on',
        'Put away the allergen signs',
        'Wipe down the fruit bar',
        'Wipe down all the condiment bars',
        'Wipe down the condiment area of the salad bar',
        'Move salad bar condiments to the student table',
      ],
    },
  },
  'Lunch': {
    'Sack Cashier': {
      'Setup': [
        'Put out soups',
        'Ensure sandwiches are available (not displayed)',
        'Put out cookies',
        'Put out chips',
        'Ensure salads are available',
        'Turn on cooler lights',
        'Unlock door when doors open',
        'Flip sign to "Open"',
        'Set up and sign into register',
      ],
      'During Shift': [
        'Ensure missionaries swipe cards',
        'Keep count of missionaries who do not swipe',
        'Ring up senior missionaries',
        'Communicate with sack runner when items run out',
      ],
      'Cleanup': [
        'Flip sign to "Closed"',
        'Lock door',
        'Log out of register',
        'Turn off cooler lights',
        'Restock drinks',
        'Restock sandwiches',
        'Restock salads',
        'Wipe counters',
        'Vacuum area',
      ],
    },
    'Sack Runner': {
      'Setup': ['Assist sack cashier with setup tasks'],
      'During Shift': [
        'Restock items from sack room as needed',
        'Coordinate with sack cashier',
      ],
      'Cleanup': ['Assist sack cashier with cleanup tasks'],
    },
    'Salads': {
      'Setup': [
        'Put out salad ingredients',
        'Put out tortillas',
        'Set up deli bar',
        'Ensure plates are stocked',
      ],
      'During Shift': [
        'Keep salad bar stocked',
        'Ensure plates remain stocked',
      ],
      'Cleanup': [
        'Surfaces cleaned',
        'Soup area clean',
        'Fridges wiped out',
        'Floor swept in and out of island',
        'Bowls/plates restocked',
        'Fruit shelf restocked',
        'Lettuce wraps/dressings restocked',
        'Trash emptied',
      ],
    },
    'Server': {
      'Setup': [
        'Follow the line map and set up the serving line',
        'Make sure the display plate has been put out',
        'Put 6 plates or 10 bowls out onto the hot pad before the doors open',
      ],
      'During Shift': [
        'Serve the food',
        'Communicate your needs to the runner as they come up',
      ],
      'Cleanup': [
        'Clean up the serving line and make sure the heaters and light are turned off',
      ],
    },
    'Ice Cream': {
      'Setup': [
        'Get ice cream',
        'Get scoops',
        'Get bowls',
        'Get water as needed',
      ],
      'During Shift': ['Serve ice cream'],
      'Cleanup': [
        'Dirty trays/utensils taken to scullery',
        'Dessert plates restocked',
        'Desserts put away in correct spot',
        'Counters/surfaces cleaned and dried',
        'Floor swept',
        'Cereal bowls restocked',
        'Silverware restocked',
      ],
    },
    'Paninis': {
      'Setup': ['Turn on panini machines'],
      'During Shift': [
        'Prepare paninis',
        'Press paninis in machines',
        'Cut paninis',
        'Put paninis out for service',
      ],
      'Cleanup': [
        'Panini presses and tools cleaned',
        'Surfaces wiped and floor swept',
        'Heated shelf off and cleaned',
      ],
    },
    'Line Running (Left)': {
      'Setup': [
        'Fill wells with water',
        'Turn on heat',
        'Turn on heating elements',
        'Put food out in correct order',
        'Get utensils',
        'Prepare plate stacks',
      ],
      'During Shift': [
        'Keep food stocked',
        'Communicate with chefs as needed',
        'Put plates out 10 at a time',
        'Keep track of plate counts',
      ],
      'Cleanup': [
        'Plates/bowls restocked',
        'Heaters off',
        'Surfaces clean and dry',
        'Drain closed and bucket empty',
        'Floors swept (including under station)',
        'Trash emptied',
      ],
    },
    'Line Running (Right)': {
      'Setup': [
        'Fill wells with water',
        'Turn on heat',
        'Turn on heating elements',
        'Put food out in correct order',
        'Get utensils',
        'Prepare plate stacks',
      ],
      'During Shift': [
        'Keep food stocked',
        'Communicate with chefs as needed',
        'Put plates out 10 at a time',
        'Keep track of plate counts',
      ],
      'Cleanup': [
        'Plates/bowls restocked',
        'Heaters off',
        'Surfaces clean and dry',
        'Drain closed and bucket empty',
        'Floors swept (including under station)',
        'Trash emptied',
      ],
    },
    'Aloha Plate': {
      'Setup': [
        'Fill wells with water',
        'Turn on heat',
        'Turn on heating elements',
        'Put food out in correct order',
        'Get utensils',
        'Prepare plate stacks',
      ],
      'During Shift': [
        'Keep food stocked',
        'Communicate with chefs as needed',
        'Put plates out 10 at a time',
        'Keep track of plate counts',
      ],
      'Cleanup': [
        'Plates/bowls restocked',
        'Heaters off',
        'Surfaces clean and dry',
        'Drain closed and bucket empty',
        'Floors swept (including under station)',
        'Trash emptied',
      ],
    },
    'Choices': {
      'Setup': [
        'Fill wells with water',
        'Turn on heat',
        'Turn on heating elements',
        'Put food out in correct order',
        'Get utensils',
        'Prepare plate stacks',
      ],
      'During Shift': [
        'Keep food stocked',
        'Communicate with chefs as needed',
        'Put plates out 10 at a time',
        'Keep track of plate counts',
      ],
      'Cleanup': [
        'Plates/bowls restocked',
        'Heaters off',
        'Surfaces clean and dry',
        'Drain closed and bucket empty',
        'Floors swept (including under station)',
        'Trash emptied',
      ],
    },
    'Beverages': {
      'Setup': [
        'Ensure all beverages are stocked',
        'Turn on beverage machines',
      ],
      'During Shift': [
        'Restock cups',
        'Check bib room for soda stock',
        'Ensure sodas are stocked',
        'Ensure juices are stocked',
        'Ensure all beverage stations remain stocked',
      ],
      'Cleanup': [
        'Milks and juices restocked',
        'Milk/soda/juice machines cleaned',
        'Cups filled',
        'Ice filled',
        'Scissors cleaned',
        'Milk trays cleaned',
        'Coke machine nozzles (dinner)',
        'Blue crates to Empire Crate Building',
        'Empire Crate Building wrapped',
        'Vitamin waters restocked',
        'BIB room checked',
      ],
    },
    'Senior Cash': {
      'Setup': ['Sign into register', 'Verify register is ready'],
      'During Shift': ['Ring up senior missionaries'],
      'Cleanup': [
        'Napkins and salt/pepper',
        'Sanitizer and paper towels',
        'Lost and found items to front desk',
        'Write next meal menu on door',
        'Refill sanitizer bottles',
        'Sweep tile floor',
      ],
    },
    'Junior Cash': {
      'Setup': ['Sign into register'],
      'During Shift': [
        'Ensure missionaries swipe cards',
        'Keep count of missionaries without cards',
      ],
      'Cleanup': [
        'Napkins and salt/pepper',
        'Sanitizer and paper towels',
        'Lost and found items to front desk',
        'Write next meal menu on door',
        'Refill sanitizer bottles',
        'Sweep tile floor',
      ],
    },
    'Desserts': {
      'Setup': [
        'Put out desserts',
        'Breakfast: donuts',
        'Lunch/Dinner: cookies or assigned desserts',
        'Put out plates',
        'Put out utensils',
      ],
      'During Shift': ['Keep desserts stocked', 'Keep utensils stocked'],
      'Cleanup': [
        'Dirty trays/utensils taken to scullery',
        'Dessert plates restocked',
        'Desserts put away in correct spot',
        'Counters/surfaces cleaned and dried',
        'Floor swept',
        'Cereal bowls restocked',
        'Silverware restocked',
      ],
    },
    'Condiments Prep': {
      'Setup': [
        'Ensure condiment cart is full',
        'Assist condiments host with setup',
      ],
      'During Shift': [
        'Keep condiments stocked',
        'Prepare condiments for next meal',
        'If dinner: prepare condiments for breakfast bar next day',
      ],
      'Cleanup': [
        'Enough prepped for next meal',
        'Specialty condiments prepped',
        'PB, J, and butter prepped',
        'Prep surfaces cleaned and dried',
        'Toaster station cleaned and restocked',
        'Condiment dispensers clean and full',
        'Pump station swept under',
        'Fruit bar surfaces cleaned and dried',
        'Bowls/plates restocked on fruit bar',
      ],
    },
    'Condiments Host': {
      'Setup': [
        'Turn on fruit bar cooler',
        'Put out fruit (4 shotgun pans of fruit, 2 of specialty food)',
        'Put out any special condiments to salad bar',
        'Put up allergen signs',
        'Put utensils in the peanut butter, and butter next to Aloha plate',
        'Make sure the condiment stands are stocked',
        'Put spoons in the fruit',
      ],
      'During Shift': [
        'Ensure everything stays stocked: fruit, condiments, and salad bar condiments',
      ],
      'Cleanup': [
        'Wrap and put away the specialty food',
        'Wrap the fruit, leave it in place, and leave the cooler on',
        'Put away the allergen signs',
        'Wipe down the fruit bar',
        'Wipe down all the condiment bars',
        'Wipe down the condiment area of the salad bar',
        'Move salad bar condiments to the student table',
      ],
    },
  },
  'Dinner': {
    'Server': {
      'Setup': [
        'Follow the line map and set up the serving line',
        'Make sure the display plate has been put out',
        'Put 6 plates or 10 bowls out onto the hot pad before the doors open',
      ],
      'During Shift': [
        'Serve the food',
        'Communicate your needs to the runner as they come up',
      ],
      'Cleanup': [
        'Clean up the serving line and make sure the heaters and light are turned off',
      ],
    },
    'Ice Cream': {
      'Setup': [
        'Get ice cream',
        'Get scoops',
        'Get bowls',
        'Get water as needed',
      ],
      'During Shift': ['Serve ice cream'],
      'Cleanup': [
        'Dirty trays/utensils taken to scullery',
        'Dessert plates restocked',
        'Desserts put away in correct spot',
        'Counters/surfaces cleaned and dried',
        'Floor swept',
        'Cereal bowls restocked',
        'Silverware restocked',
      ],
    },
    'Paninis': {
      'Setup': ['Turn on panini machines'],
      'During Shift': [
        'Prepare paninis',
        'Press paninis in machines',
        'Cut paninis',
        'Put paninis out for service',
      ],
      'Cleanup': [
        'Panini presses and tools cleaned',
        'Surfaces wiped and floor swept',
        'Heated shelf off and cleaned',
      ],
    },
    'Line Running (Left)': {
      'Setup': [
        'Fill wells with water',
        'Turn on heat',
        'Turn on heating elements',
        'Put food out in correct order',
        'Get utensils',
        'Prepare plate stacks',
      ],
      'During Shift': [
        'Keep food stocked',
        'Communicate with chefs as needed',
        'Put plates out 10 at a time',
        'Keep track of plate counts',
      ],
      'Cleanup': [
        'Plates/bowls restocked',
        'Heaters off',
        'Surfaces clean and dry',
        'Drain closed and bucket empty',
        'Floors swept (including under station)',
        'Trash emptied',
      ],
    },
    'Line Running (Right)': {
      'Setup': [
        'Fill wells with water',
        'Turn on heat',
        'Turn on heating elements',
        'Put food out in correct order',
        'Get utensils',
        'Prepare plate stacks',
      ],
      'During Shift': [
        'Keep food stocked',
        'Communicate with chefs as needed',
        'Put plates out 10 at a time',
        'Keep track of plate counts',
      ],
      'Cleanup': [
        'Plates/bowls restocked',
        'Heaters off',
        'Surfaces clean and dry',
        'Drain closed and bucket empty',
        'Floors swept (including under station)',
        'Trash emptied',
      ],
    },
    'Aloha Plate': {
      'Setup': [
        'Fill wells with water',
        'Turn on heat',
        'Turn on heating elements',
        'Put food out in correct order',
        'Get utensils',
        'Prepare plate stacks',
      ],
      'During Shift': [
        'Keep food stocked',
        'Communicate with chefs as needed',
        'Put plates out 10 at a time',
        'Keep track of plate counts',
      ],
      'Cleanup': [
        'Plates/bowls restocked',
        'Heaters off',
        'Surfaces clean and dry',
        'Drain closed and bucket empty',
        'Floors swept (including under station)',
        'Trash emptied',
      ],
    },
    'Choices': {
      'Setup': [
        'Fill wells with water',
        'Turn on heat',
        'Turn on heating elements',
        'Put food out in correct order',
        'Get utensils',
        'Prepare plate stacks',
      ],
      'During Shift': [
        'Keep food stocked',
        'Communicate with chefs as needed',
        'Put plates out 10 at a time',
        'Keep track of plate counts',
      ],
      'Cleanup': [
        'Plates/bowls restocked',
        'Heaters off',
        'Surfaces clean and dry',
        'Drain closed and bucket empty',
        'Floors swept (including under station)',
        'Trash emptied',
      ],
    },
    'Beverages': {
      'Setup': [
        'Ensure all beverages are stocked',
        'Turn on beverage machines',
      ],
      'During Shift': [
        'Restock cups',
        'Check bib room for soda stock',
        'Ensure sodas are stocked',
        'Ensure juices are stocked',
        'Ensure all beverage stations remain stocked',
      ],
      'Cleanup': [
        'Milks and juices restocked',
        'Milk/soda/juice machines cleaned',
        'Cups filled',
        'Ice filled',
        'Scissors cleaned',
        'Milk trays cleaned',
        'Coke machine nozzles (dinner)',
        'Blue crates to Empire Crate Building',
        'Empire Crate Building wrapped',
        'Vitamin waters restocked',
        'BIB room checked',
      ],
    },
    'Senior Cash': {
      'Setup': ['Sign into register', 'Verify register is ready'],
      'During Shift': ['Ring up senior missionaries'],
      'Cleanup': [
        'Napkins and salt/pepper',
        'Sanitizer and paper towels',
        'Lost and found items to front desk',
        'Write next meal menu on door',
        'Refill sanitizer bottles',
        'Sweep tile floor',
      ],
    },
    'Junior Cash': {
      'Setup': ['Sign into register'],
      'During Shift': [
        'Ensure missionaries swipe cards',
        'Keep count of missionaries without cards',
      ],
      'Cleanup': [
        'Napkins and salt/pepper',
        'Sanitizer and paper towels',
        'Lost and found items to front desk',
        'Write next meal menu on door',
        'Refill sanitizer bottles',
        'Sweep tile floor',
      ],
    },
    'Desserts': {
      'Setup': [
        'Put out desserts',
        'Breakfast: donuts',
        'Lunch/Dinner: cookies or assigned desserts',
        'Put out plates',
        'Put out utensils',
      ],
      'During Shift': ['Keep desserts stocked', 'Keep utensils stocked'],
      'Cleanup': [
        'Dirty trays/utensils taken to scullery',
        'Dessert plates restocked',
        'Desserts put away in correct spot',
        'Counters/surfaces cleaned and dried',
        'Floor swept',
        'Cereal bowls restocked',
        'Silverware restocked',
      ],
    },
    'Condiments Prep': {
      'Setup': [
        'Ensure condiment cart is full',
        'Assist condiments host with setup',
      ],
      'During Shift': [
        'Keep condiments stocked',
        'Prepare condiments for next meal',
        'If dinner: prepare condiments for breakfast bar next day',
      ],
      'Cleanup': [
        'Enough prepped for next meal',
        'Specialty condiments prepped',
        'PB, J, and butter prepped',
        'Prep surfaces cleaned and dried',
        'Toaster station cleaned and restocked',
        'Condiment dispensers clean and full',
        'Pump station swept under',
        'Fruit bar surfaces cleaned and dried',
        'Bowls/plates restocked on fruit bar',
      ],
    },
    'Condiments Host': {
      'Setup': [
        'Turn on fruit bar cooler',
        'Put out fruit (4 shotgun pans of fruit, 2 of specialty food)',
        'Put out any special condiments to salad bar',
        'Put up allergen signs',
        'Put utensils in the peanut butter, and butter next to Aloha plate',
        'Make sure the condiment stands are stocked',
        'Put spoons in the fruit',
      ],
      'During Shift': [
        'Ensure everything stays stocked: fruit, condiments, and salad bar condiments',
      ],
      'Cleanup': [
        'Wrap and put away the specialty food',
        'Wrap the fruit, leave it in place, and leave the cooler on',
        'Put away the allergen signs',
        'Wipe down the fruit bar',
        'Wipe down all the condiment bars',
        'Wipe down the condiment area of the salad bar',
        'Move salad bar condiments to the student table',
      ],
    },
  },
};
